### ISSUE TITLE
Toy-Example Notebook gives InvalidArgumentError

### ISSUE THREAD

**Issue by jzenn** [artsobolev/IWHVI#1]
Hi!

Thank you so much for publishing the code to re-produce your results! I am currently trying to run the Google Colab notebook. However, I get `InvalidArgumentError: Operation 'Gamma_1/sample/random_gamma/RandomGamma' has no attr named '_XlaCompile'.` in cell 13. Do you have any idea on how I could fix this?
Thank you very much in advance!

Best,
Johannes

**Comment by artsobolev** [comment]
Hi @jzenn,

It appears the Colab is not very good at keeping previous versions and is even going to discontinue the TF 1.x in near future. I therefore suggest you to just download the ipynb file and run it locally in a jupyter notebook using `tensorflow==1.14 tensorflow-gpu==1.14 tensorflow-probability==0.7`

**Comment by jzenn** [comment]
Hi @artsobolev,

Thank you very much for this prompt response. I will do that and close this issue when your suggestion works!

**Comment by jzenn** [comment]
Locally, the notebook seems to be working, thank you for your help!
